apiVersion: v1
kind: Service
metadata:
  name: client-test-service
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: http://auth-service-service.default.svc.cluster.local:5000/verify
    ingress.kubernetes.io/auth-response-headers: UserID, IsAdmin, UserRoles
spec:
  selector:
    app: client-test-1
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP