apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: server-test-service-profile
  namespace: default
spec:
  routes:
  - condition:
      method: POST
      pathRegex: /message
    name: POST /message
    isRetryable: true